# .dlt/secrets.toml
# NÃO commite este arquivo no git

# ── PostgreSQL ───────────────────────────────────────────────
# Credenciais injetadas via variáveis de ambiente do Airflow
[sources.sql_database.credentials]
drivername = "postgresql+psycopg2"
host       = ""
port       = 5432
database   = ""
username   = ""
password   = ""


# ── S3 Tables ───────────────────────────────────────────────
[destination.filesystem]
bucket_url = "s3://datahandson-lakehouse-duckdb"

[destination.filesystem.credentials]
aws_access_key_id     = ""
aws_secret_access_key = ""
region_name           = "us-east-2"

[iceberg_catalog]
iceberg_catalog_name = "s3tables"
iceberg_catalog_type = "rest"

[iceberg_catalog.iceberg_catalog_config]
type                  = "rest"
uri                   = "https://s3tables.us-east-2.amazonaws.com/iceberg"
warehouse             = "arn:aws:s3tables:us-east-2:296735965303:bucket/datahandson-lakehouse-duckdb"
"rest.sigv4-enabled"  = "true"
"rest.signing-name"   = "s3tables"
"rest.signing-region" = "us-east-2"
s3.access-key-id      = ""
s3.secret-access-key  = ""
s3.region             = "us-east-2"

